#include "A.h"




void A::perimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--4a651011:16d84887350:-8000:0000000000000978 begin
{
}
// section -64--88-56-1--4a651011:16d84887350:-8000:0000000000000978 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void A::aire()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--4a651011:16d84887350:-8000:000000000000097A begin
{
}
// section -64--88-56-1--4a651011:16d84887350:-8000:000000000000097A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
